// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caafbktgwdltioctdued.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhYWZia3Rnd2RsdGlvY3RkdWVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNjk2OTcsImV4cCI6MjA3Mzc0NTY5N30.UXNxdc4S2O4uKxxpd7UcxmlZ6QbDloSap6aStGeezPs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});